package com.healios.dreams.model.challenge

enum class Challenge(val code: Int) {

    TWOMINWALK(1),
    MUSICALCHAIRS(2),
    WOBBLER(3),
    TIGHTROPE(4),
    CLIMBINGSTAIRS(5),
    UTURN(6),
    ROCHE_TWOMINUTEWALK(7),
    ROCHE_UTURN(8),
    CATCHACLOUD(9),
    SCREENTONOSE(10),
    ROCHE_PINCHATOMATO(11),
    ROCHE_DRAWSHAPE(12),
    PEAK_FLDO(13),
    PEAK_FLDOR(14),
    SDMT(15),
    ROCHE_SDMT(16),
    PEAK_WOHU(17),
    PEAK_SPCY(18),
    PEAK_ZAGA(19),
    PEAK_FASW(20),
    PEAK_RUBA(21),
    PEAK_BACL(22),
    PEAK_PEPA(23),
    PEAK_PUBL(24),
    PEAK_MUSO(25),
    PEAK_LOPO(26),
    ACUITY(27),
    CONTRAST(28),
    MSIS(29),
    MSWS(30),
    FSS(31),
    MSST(32)
}